##Nathan Hinton
# This file was generated from addImageset.py

from PIL import Image, ImageTk
from pickle import load

print('loading image set 4 from database...')
try:
    A42load, B42load, C42load, D42load, E42load, F42load, G42load, H42load, I42load, J42load, K42load, L42load, M42load, N42load, O42load, P42load, Q42load, R42load, S42load, T42load, U42load, V42load, W42load, X42load, Y42load, Z42load, A4load, B4load, C4load, D4load, E4load, F4load, G4load, H4load, I4load, J4load, K4load, L4load, M4load, N4load, O4load, P4load, Q4load, R4load, S4load, T4load, U4load, V4load, W4load, X4load, Y4load, Z4load = load(open('imageSet4.pk', 'rb'))
except FileNotFoundError:
    from util.addImageset import generateNewImages
    generateNewImages(4)
A4render = ImageTk.PhotoImage(A4load)
A42render = ImageTk.PhotoImage(A42load)
B4render = ImageTk.PhotoImage(B4load)
B42render = ImageTk.PhotoImage(B42load)
C4render = ImageTk.PhotoImage(C4load)
C42render = ImageTk.PhotoImage(C42load)
D4render = ImageTk.PhotoImage(D4load)
D42render = ImageTk.PhotoImage(D42load)
E4render = ImageTk.PhotoImage(E4load)
E42render = ImageTk.PhotoImage(E42load)
F4render = ImageTk.PhotoImage(F4load)
F42render = ImageTk.PhotoImage(F42load)
G4render = ImageTk.PhotoImage(G4load)
G42render = ImageTk.PhotoImage(G42load)
H4render = ImageTk.PhotoImage(H4load)
H42render = ImageTk.PhotoImage(H42load)
I4render = ImageTk.PhotoImage(I4load)
I42render = ImageTk.PhotoImage(I42load)
J4render = ImageTk.PhotoImage(J4load)
J42render = ImageTk.PhotoImage(J42load)
K4render = ImageTk.PhotoImage(K4load)
K42render = ImageTk.PhotoImage(K42load)
L4render = ImageTk.PhotoImage(L4load)
L42render = ImageTk.PhotoImage(L42load)
M4render = ImageTk.PhotoImage(M4load)
M42render = ImageTk.PhotoImage(M42load)
N4render = ImageTk.PhotoImage(N4load)
N42render = ImageTk.PhotoImage(N42load)
O4render = ImageTk.PhotoImage(O4load)
O42render = ImageTk.PhotoImage(O42load)
P4render = ImageTk.PhotoImage(P4load)
P42render = ImageTk.PhotoImage(P42load)
Q4render = ImageTk.PhotoImage(Q4load)
Q42render = ImageTk.PhotoImage(Q42load)
R4render = ImageTk.PhotoImage(R4load)
R42render = ImageTk.PhotoImage(R42load)
S4render = ImageTk.PhotoImage(S4load)
S42render = ImageTk.PhotoImage(S42load)
T4render = ImageTk.PhotoImage(T4load)
T42render = ImageTk.PhotoImage(T42load)
U4render = ImageTk.PhotoImage(U4load)
U42render = ImageTk.PhotoImage(U42load)
V4render = ImageTk.PhotoImage(V4load)
V42render = ImageTk.PhotoImage(V42load)
W4render = ImageTk.PhotoImage(W4load)
W42render = ImageTk.PhotoImage(W42load)
X4render = ImageTk.PhotoImage(X4load)
X42render = ImageTk.PhotoImage(X42load)
Y4render = ImageTk.PhotoImage(Y4load)
Y42render = ImageTk.PhotoImage(Y42load)
Z4render = ImageTk.PhotoImage(Z4load)
Z42render = ImageTk.PhotoImage(Z42load)
