##Nathan Hinton
# This file was generated from addImageset.py

from PIL import Image, ImageTk
from pickle import load

print('loading image set 3 from database...')
try:
    A32load, B32load, C32load, D32load, E32load, F32load, G32load, H32load, I32load, J32load, K32load, L32load, M32load, N32load, O32load, P32load, Q32load, R32load, S32load, T32load, U32load, V32load, W32load, X32load, Y32load, Z32load, A3load, B3load, C3load, D3load, E3load, F3load, G3load, H3load, I3load, J3load, K3load, L3load, M3load, N3load, O3load, P3load, Q3load, R3load, S3load, T3load, U3load, V3load, W3load, X3load, Y3load, Z3load = load(open('imageSet3.pk', 'rb'))
except FileNotFoundError:
    from util.addImageset import generateNewImages
    generateNewImages(3)
A3render = ImageTk.PhotoImage(A3load)
A32render = ImageTk.PhotoImage(A32load)
B3render = ImageTk.PhotoImage(B3load)
B32render = ImageTk.PhotoImage(B32load)
C3render = ImageTk.PhotoImage(C3load)
C32render = ImageTk.PhotoImage(C32load)
D3render = ImageTk.PhotoImage(D3load)
D32render = ImageTk.PhotoImage(D32load)
E3render = ImageTk.PhotoImage(E3load)
E32render = ImageTk.PhotoImage(E32load)
F3render = ImageTk.PhotoImage(F3load)
F32render = ImageTk.PhotoImage(F32load)
G3render = ImageTk.PhotoImage(G3load)
G32render = ImageTk.PhotoImage(G32load)
H3render = ImageTk.PhotoImage(H3load)
H32render = ImageTk.PhotoImage(H32load)
I3render = ImageTk.PhotoImage(I3load)
I32render = ImageTk.PhotoImage(I32load)
J3render = ImageTk.PhotoImage(J3load)
J32render = ImageTk.PhotoImage(J32load)
K3render = ImageTk.PhotoImage(K3load)
K32render = ImageTk.PhotoImage(K32load)
L3render = ImageTk.PhotoImage(L3load)
L32render = ImageTk.PhotoImage(L32load)
M3render = ImageTk.PhotoImage(M3load)
M32render = ImageTk.PhotoImage(M32load)
N3render = ImageTk.PhotoImage(N3load)
N32render = ImageTk.PhotoImage(N32load)
O3render = ImageTk.PhotoImage(O3load)
O32render = ImageTk.PhotoImage(O32load)
P3render = ImageTk.PhotoImage(P3load)
P32render = ImageTk.PhotoImage(P32load)
Q3render = ImageTk.PhotoImage(Q3load)
Q32render = ImageTk.PhotoImage(Q32load)
R3render = ImageTk.PhotoImage(R3load)
R32render = ImageTk.PhotoImage(R32load)
S3render = ImageTk.PhotoImage(S3load)
S32render = ImageTk.PhotoImage(S32load)
T3render = ImageTk.PhotoImage(T3load)
T32render = ImageTk.PhotoImage(T32load)
U3render = ImageTk.PhotoImage(U3load)
U32render = ImageTk.PhotoImage(U32load)
V3render = ImageTk.PhotoImage(V3load)
V32render = ImageTk.PhotoImage(V32load)
W3render = ImageTk.PhotoImage(W3load)
W32render = ImageTk.PhotoImage(W32load)
X3render = ImageTk.PhotoImage(X3load)
X32render = ImageTk.PhotoImage(X32load)
Y3render = ImageTk.PhotoImage(Y3load)
Y32render = ImageTk.PhotoImage(Y32load)
Z3render = ImageTk.PhotoImage(Z3load)
Z32render = ImageTk.PhotoImage(Z32load)
